config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :problems do
    resources :solutions
  end
  authenticated do
    root to: 'home#search', as: :authenticated_root
  end
  root to: 'home#index'
  get '/payments/success', to: 'payments#success'
  post '/payments/webhooks', to: 'payments#webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :user
  has_many :solutions, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 500 }
  validates :category, presence: true

  scope :search_by_categories, ->(category) { where(category: category) }
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :problem
  belongs_to :user
  has_one_attached :image
  has_one_attached :document

  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :problems
  has_many :solutions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def search
  #Query enables search of problems category and redirects to index page
    if params[:search].present?
      redirect_to problems_path
    else
      render 'search'
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhooks]

  def success; end

  def webhooks
    payment_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    render plain: 'Success'
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_problem, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
  #Query searches category column of problem table for full/partial matches from user entered data
    @problems = if params[:search].present?
                  @problems = Problem.where('category ILIKE ?', "%#{params[:search][:category]}%")
                else
                  Problem.all
                end
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = current_user.problems.new(problem_params)
    if @problem.save
      redirect_to problem_path(@problem.id)
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @problem.update(problem_params)
    redirect_to problem_path(@problem[:id])
  end

  def destroy
    @problem.destroy
    redirect_to problems_path
  end

  private

  def set_problem
    @problem = Problem.includes(solutions: [image_attachment: :blob]).find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:title, :body, :category, :image)
  end

  def authorize_user!
    redirect_to problems_path(params[:problem_id]) unless @problem.user == current_user
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_solution, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @solutions = Solution.all.includes([:image_attachment], [:document_attachment])
  end

  def new
    @solution = Solution.new
  end

  def create
    @problem = Problem.find(params[:problem_id])
    @solution = @problem.solutions.new(solution_params)
    @solution.user = current_user
    if @solution.save
      redirect_to problem_solution_path(@problem, @solution)
    else 
      render 'new'
    end 
  end

  def show
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: [{
        price_data: {
          currency: 'aud',
          product_data: {
            name: @solution.title
          },
          unit_amount: (@solution.price * 100).to_i
        },
        quantity: 1
      }],
      mode: 'payment',
      success_url: "#{root_url}payments/success?solutionId=#{@solution.id}",
      cancel_url: "#{root_url}solutions"
    )
    @session_id = session.id
  end

  def edit
    @problem_id = params[:problem_id]
  end

  def update
    @solution.update(solution_params)
    redirect_to problem_solutions_path
  end

  def destroy
    @solution.destroy
    redirect_to problem_solutions_path
  end

  private

  def set_solution
    @solution = Solution.find(params[:id])
  end

  def solution_params
    params.require(:solution).permit(:title, :body, :image, :document, :price)
  end

  def authorize_user!
    redirect_to problem_solutions_path(params[:problem_id]) unless @solution.user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class_for(alert_level)
    case alert_level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-warning'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/home/index.html.erb
<div class="row home-index">
  <h1 class="col-3 text-right">Minimalist</h1>
</div>
<div class="row">
  <h1 class="col-4 text-right" >Apartment</h1><h3 class="col-4 text-right"><%= link_to 'Sign In', new_user_session_path %></h4>
</div>
<div class="row">
  <h1 class="col-4 text-right" >Living</h1><h4 class="col-4 text-right"><%= link_to 'Sign Up', new_user_registration_path %></h4>
</div>
<div class="col-6 text-right">
  <p> Blog Link Here </p>
</div>
<div class="row fixed-bottom justify-content-center home-index"> 
  <h1 class="col"> a community of apartment enthusiasts</h1>
</div>

app/views/home/search.html.erb
<%= render 'shared/nav' %>
<div class="row align-center">
  <div class="col-6">
  <div class="card">
  <div class="card-body text-center">
    <p> Search our database to see if someone else has encountered the same challenge as you...</p>
    <%= form_with(scope: :search, url: problems_path, method: 'get', local: true) do |f| %>
    <h4><%= f.text_field :category, placeholder: 'Where is the challenge you are facing?' %></h4>
    <%= f.submit 'Search' %>
    <% end %>
  </div>
  <div class="text-center">
  <p> Can't find what you're looking for?</p>
  <p> List your own challenge </p>
  <%= link_to 'Challenge Accepted', new_problem_path %>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minliving</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minliving</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="home">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/problems.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minliving</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container-fluid">
      <%= yield %>
      <h1 class="row fixed-bottom justify-content-end">Challenges</h1>
    </div>
  </body>
</html>

app/views/layouts/solutions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minliving</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="solution-body">
    <%= render 'shared/nav' %>
    <div class="container-fluid">
      <%= yield %>
    <h1 class="row fixed-bottom justify-content-end"> Solutions</h1>
    </div>
  </body>
</html>

app/views/payments/success.html.erb
<h3> You’ve successfully made a payment! </h3>
<h3> You will receive your pdf instructions via email shortly </h3>
<%= link_to "Return to Challenges", problems_path %>

app/views/problems/_form.html.erb
<%= form_with model: @problem, local: true do |f| %>
  <% if @problem.errors.any? %>
    <div class="row" id="error_explanation">
      <h2><% pluralize(@problem.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% @problem.errors.full_messages.each do|msg| %>
          <li><%= msg %></li>
            <% end %>
          </ul>
      <% end %>
    </div>
    <div class="row">
    <div class="col text-center">
      <div class="btn-group-vertical">
        <h4><%= f.radio_button(:category, "Hallway") %> Hallway </h4>
        <h4><%= f.radio_button(:category, "Kitchen") %> Kitchen </h4>
        <h4><%= f.radio_button(:category, "Bathroom") %> Bathroom </h4>
        <h4><%= f.radio_button(:category, "Living") %> Living </h4>
        <h4><%= f.radio_button(:category, "Bedroom") %> Bedroom </h4>
        <h4><%= f.radio_button(:category, "Study") %> Study </h4>
        <h4><%= f.radio_button(:category, "Laundry") %> Laundry </h4>
        <h4><%= f.radio_button(:category, "Balcony") %> Balcony </h4>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <div class="card-header"><%= f.text_field :title, placeholder: 'Challenge Heading' %></div>
        <div class="card-body"><%= f.text_area :body, placeholder: 'Please provide a short description of the challenge you are facing...' %></div>
      </div>
    </div>
    <div class="col text-center">
      <h5>"Image"</h5>
      <h5><%= f.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %></h5>
        <%= f.submit 'List Challenge'%>
    </div>
  </div>
<% end %>

app/views/problems/edit.html.erb
<%= render 'form', {problem: @problem} %>

app/views/problems/index.html.erb
<div class="row">
  <div class="col-md-6 ml-auto" >
    <% @problems.each do |problem| %>
    <div class="card-header"> <%= link_to problem.title, problem_path(problem.id) %> </div>
    <div class="card-body"><%= problem.body %></div>
    <% end %>
  </div>
</div>
</div>

app/views/problems/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3 text-right">
    <%= form_with scope: :problem, url: problems_path, method: 'post', local: true do |f| %>
      <div class="card" id="problems-card">
        <%= f.text_field :title, placeholder: 'Title' %>
        <%= f.text_area :body, size: '65', placeholder: 'What is the challenge you are facing?' %>
        <%= f.text_field :category, placeholder: 'category' %>
      </div>
      <div>
        <p> Please upload an image to help others visualise your challenge </p>
          <%= f.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %>
        <p class="text-center"> <%= f.submit 'Submit Challenge' %> </p>
      </div>
    <% end %>
  </div>
</div>

app/views/problems/show.html.erb
<div class="row">
  <div class="col-6">
    <div style="width: 100%;">
      <%= image_tag 'skyscrapers.jpg'%>
    </div>
  </div>
  <div class="col-6" >
    <% if @problem.image.attached? %>
      <%= image_tag @problem.image %>
    <% else %> 
      <%= image_tag 'p-placeholder.jpg' %>
    <% end %> 
    <h5 class="card-header"><%= @problem.title %></h5>
    <% if current_user[:id] == @problem.user_id %>
      <%= link_to 'Edit', edit_problem_path(@problem.id) %>
      <%= link_to 'Delete', problem_path(@problem.id), method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
    <p class="card-body"><%= @problem.body %></p>
    <%= link_to 'Suggest Solution', new_problem_solution_path(@problem.id) %>

    <h1> Solutions </h1>
    <div class="card">
      <% @problem.solutions.each do |solution| %>
        <% if solution.image.attached? %>
          <div class="card"><%= image_tag solution.image %></div>
        <% else %>
          <%= image_tag 's-placeholder.jpg'%>
        <% end %>
        <h5 class="card-header"><%= solution.title %></h5>
        <p class="card-body"><%= solution.body %></p>
        <%= link_to 'Purchase this Solution', problem_solution_path(@problem.id) %>
        <% if current_user == @problem.user_id %>
        <%= link_to 'Edit', edit_problem_solution_path(@problem.id, solution.id) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |level, message| %>
  <div class="<%= flash_class_for(level) %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<ul class="nav">
  <li class="nav-item">
    <div class="nav-link active"> <%= link_to 'See All Challenges', problems_path %></div>
  </li>
  <li class="nav-item">
    <div class="nav-link"> <%= link_to 'Search Challenges', authenticated_root_path %></div>
  </li>
  <li class="nav-item">
    <div class="nav-link"> <%= link_to 'List New Challenge', new_problem_path %></div>
  </li>
  <li class="nav-item">
    <div class="nav-link"> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </div>
  </li>
  <li class="nav-item">
    <div class="nav-link disabled">Blog</div>
  </li>
</ul>

app/views/solutions/_form.html.erb
<%= form_with model: solution, url: problem_solution_path(problem_id), local: true do |f| %>
  <% if solution.errors.any? %>
    <div class="row" id="error_explanation">
    <h2><% pluralize(solution.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
      <% solution.errors.full_messages.each do|msg| %>
        <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :body %>
<%= f.text_area :body %>
<%= f.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %>
<p> PDF <%= f.file_field :document, accept: 'document/pdf' %></p>
<%= f.number_field :price %>

<%= f.submit %>
<% end %>

app/views/solutions/edit.html.erb
<%= render 'form', solution: @solution, problem_id: @problem_id %>

app/views/solutions/index.html.erb
<% @solutions.each do |solution| %>
<p>Title: <%= solution.title %> </p>
<p>Solution: <%= solution.body %> </p>
<% if solution.image.attached? %>
<p>Image: <%= image_tag solution.image %> </p>
<% else %>
<p> No image attached </p>
<% end %>
<% if solution.document.attached? %>
<p>This solution has a pdf available to purchase for $<%=solution.price%></p>
<% end %>
<%= link_to 'Show', problem_solution_path(solution[:problem_id], solution[:id]) %>
<%= link_to 'Edit', edit_problem_solution_path(solution[:problem_id], solution[:id]) %>
<%= link_to 'Delete', problem_solution_path(solution[:problem_id], solution[:id]), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<%= link_to 'Challenges Page', problems_path %>

app/views/solutions/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3 text-right">
    <%= form_with scope: :solution, url: problem_solutions_path, method: 'post', local: true do |f| %>
      <div class="card" id="solution-card">
        <%= f.text_field :title, placeholder: 'Title' %>
        <%= f.text_area :body, size: '65', placeholder: 'Enter your solution for the challenge here...' %>
      </div>
      <div>
        <p> Please upload an image to help others visualise your solution </p>
          <%= f.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %>
        <p> If you would like to upload and list an Instructional PDF for sale, please do so below</p>
        <p> <%= f.file_field :document, accept: 'document/pdf' %> </p>
        <p> Cost: $ <%=f.number_field :price %></p>
        <p class="text-center"> <%= f.submit 'Suggest Solution' %> </p>
      </div>
    <% end %>
  </div>
</div>

app/views/solutions/show.html.erb
<h1> Solution for</h1>
<div class="row">
<div class="col-6">
  <h3><%= @solution.title %></h3>
</div>
<div class="col-6" class="solution-image">
  <% if @solution.image.attached? %>
  <%= image_tag @solution.image %>
  <% else %> 
  <%= image_tag "s-placeholder.jpg"%>
  <% end %>
</div>
<div>
<button data-stripe="payment"> Purchase Instructional PDF <%= number_to_currency(@solution.price)%></button>
<div class="text-center"><%= link_to 'Back', :back %></div>
<script src="https://js.stripe.com/v3/"></script>

<script>
	document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
		const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
		stripe.redirectToCheckout({
			sessionId: "<%= @session_id %>"
		});
	});
</script>
</div>